-- 코드를 입력하세요
SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, 
    CASE WHEN
    ISNULL(FREEZER_YN) THEN 'N'
    WHEN FREEZER_YN = 'N' THEN 'N'
    ELSE 'Y'
    END AS FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE ADDRESS LIKE '경기%'
ORDER BY WAREHOUSE_ID
